### PR TITLE
Added timestamp

### PR DESCRIPTION
**Pull request by RaviTejaVattem**
Addresses issue #2

@vipul0425 please have a look.

### CODE REVIEW

**Comment by vipul0425** [comment]
I have merged your PR please star this project if it helped you in any way. Thanks!

**Comment by vipul0425** [comment]
@RaviTejaVattem I have merged your PR but I am not able to see the time stamp in the webpage here is the link you can check as well https://vipul0425.github.io/Calorie-Tracker/

**Comment by RaviTejaVattem** [comment]
I am seeing the timestamp from the same link.

Let me know if you have any questions

**Comment by vipul0425** [comment]
ya @RaviTejaVattem got it it was actually browser cache.

**Pull request merged**
